// Generated by CoffeeScript 1.10.0
(function() {
  module.exports = (function() {
    function _Class() {}

    _Class.prototype.rule = {
      name: 'no_multiline_addition',
      level: 'error',
      message: 'Line contains multiline addition. Swap to heredoc',
      regexList: [],
      description: '      '
    };

    _Class.prototype.lintLine = function(line, api) {
      var re;
      re = /\+\s*$/g;
      if (re.test(line)) {
        return true;
      }
    };

    return _Class;

  })();

}).call(this);
