// Generated by CoffeeScript 1.10.0
(function() {
  module.exports = (function() {
    function _Class() {}

    _Class.prototype.rule = {
      name: 'no_multiline_addition',
      level: 'error',
      message: 'Line contains multiline addition. Swap to heredoc',
      description: '      '
    };

    _Class.prototype.tokens = ['+'];

    _Class.prototype.lintToken = function(token, token_api) {
      if (token.newLine) {
        return true;
      }
    };

    return _Class;

  })();

}).call(this);

//# sourceMappingURL=index.js.map
